package me.jessyan.armscomponent.commonsdk.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import me.jessyan.armscomponent.commonsdk.bean.Historyrecord.OffLineAssetsBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OFF_LINE_ASSETS_BEAN".
*/
public class OffLineAssetsBeanDao extends AbstractDao<OffLineAssetsBean, Long> {

    public static final String TABLENAME = "OFF_LINE_ASSETS_BEAN";

    /**
     * Properties of entity OffLineAssetsBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Uid = new Property(0, Long.class, "uid", true, "_id");
        public final static Property RfidId = new Property(1, String.class, "rfidId", false, "RFID_ID");
        public final static Property AssetState = new Property(2, int.class, "assetState", false, "ASSET_STATE");
        public final static Property PermissionState = new Property(3, int.class, "permissionState", false, "PERMISSION_STATE");
        public final static Property AssetUser = new Property(4, String.class, "assetUser", false, "ASSET_USER");
        public final static Property BelongDept = new Property(5, String.class, "belongDept", false, "BELONG_DEPT");
        public final static Property LastApproveUser = new Property(6, String.class, "lastApproveUser", false, "LAST_APPROVE_USER");
        public final static Property EndTime = new Property(7, String.class, "endTime", false, "END_TIME");
        public final static Property Id = new Property(8, String.class, "id", false, "ID");
        public final static Property OutBillId = new Property(9, String.class, "outBillId", false, "OUT_BILL_ID");
        public final static Property AssetId = new Property(10, String.class, "assetId", false, "ASSET_ID");
        public final static Property AssetName = new Property(11, String.class, "assetName", false, "ASSET_NAME");
        public final static Property TypeId = new Property(12, String.class, "typeId", false, "TYPE_ID");
        public final static Property AssetBrand = new Property(13, String.class, "assetBrand", false, "ASSET_BRAND");
        public final static Property AssetModel = new Property(14, String.class, "assetModel", false, "ASSET_MODEL");
    }


    public OffLineAssetsBeanDao(DaoConfig config) {
        super(config);
    }
    
    public OffLineAssetsBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OFF_LINE_ASSETS_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: uid
                "\"RFID_ID\" TEXT," + // 1: rfidId
                "\"ASSET_STATE\" INTEGER NOT NULL ," + // 2: assetState
                "\"PERMISSION_STATE\" INTEGER NOT NULL ," + // 3: permissionState
                "\"ASSET_USER\" TEXT," + // 4: assetUser
                "\"BELONG_DEPT\" TEXT," + // 5: belongDept
                "\"LAST_APPROVE_USER\" TEXT," + // 6: lastApproveUser
                "\"END_TIME\" TEXT," + // 7: endTime
                "\"ID\" TEXT," + // 8: id
                "\"OUT_BILL_ID\" TEXT," + // 9: outBillId
                "\"ASSET_ID\" TEXT," + // 10: assetId
                "\"ASSET_NAME\" TEXT," + // 11: assetName
                "\"TYPE_ID\" TEXT," + // 12: typeId
                "\"ASSET_BRAND\" TEXT," + // 13: assetBrand
                "\"ASSET_MODEL\" TEXT);"); // 14: assetModel
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OFF_LINE_ASSETS_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OffLineAssetsBean entity) {
        stmt.clearBindings();
 
        Long uid = entity.getUid();
        if (uid != null) {
            stmt.bindLong(1, uid);
        }
 
        String rfidId = entity.getRfidId();
        if (rfidId != null) {
            stmt.bindString(2, rfidId);
        }
        stmt.bindLong(3, entity.getAssetState());
        stmt.bindLong(4, entity.getPermissionState());
 
        String assetUser = entity.getAssetUser();
        if (assetUser != null) {
            stmt.bindString(5, assetUser);
        }
 
        String belongDept = entity.getBelongDept();
        if (belongDept != null) {
            stmt.bindString(6, belongDept);
        }
 
        String lastApproveUser = entity.getLastApproveUser();
        if (lastApproveUser != null) {
            stmt.bindString(7, lastApproveUser);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(8, endTime);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(9, id);
        }
 
        String outBillId = entity.getOutBillId();
        if (outBillId != null) {
            stmt.bindString(10, outBillId);
        }
 
        String assetId = entity.getAssetId();
        if (assetId != null) {
            stmt.bindString(11, assetId);
        }
 
        String assetName = entity.getAssetName();
        if (assetName != null) {
            stmt.bindString(12, assetName);
        }
 
        String typeId = entity.getTypeId();
        if (typeId != null) {
            stmt.bindString(13, typeId);
        }
 
        String assetBrand = entity.getAssetBrand();
        if (assetBrand != null) {
            stmt.bindString(14, assetBrand);
        }
 
        String assetModel = entity.getAssetModel();
        if (assetModel != null) {
            stmt.bindString(15, assetModel);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OffLineAssetsBean entity) {
        stmt.clearBindings();
 
        Long uid = entity.getUid();
        if (uid != null) {
            stmt.bindLong(1, uid);
        }
 
        String rfidId = entity.getRfidId();
        if (rfidId != null) {
            stmt.bindString(2, rfidId);
        }
        stmt.bindLong(3, entity.getAssetState());
        stmt.bindLong(4, entity.getPermissionState());
 
        String assetUser = entity.getAssetUser();
        if (assetUser != null) {
            stmt.bindString(5, assetUser);
        }
 
        String belongDept = entity.getBelongDept();
        if (belongDept != null) {
            stmt.bindString(6, belongDept);
        }
 
        String lastApproveUser = entity.getLastApproveUser();
        if (lastApproveUser != null) {
            stmt.bindString(7, lastApproveUser);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(8, endTime);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(9, id);
        }
 
        String outBillId = entity.getOutBillId();
        if (outBillId != null) {
            stmt.bindString(10, outBillId);
        }
 
        String assetId = entity.getAssetId();
        if (assetId != null) {
            stmt.bindString(11, assetId);
        }
 
        String assetName = entity.getAssetName();
        if (assetName != null) {
            stmt.bindString(12, assetName);
        }
 
        String typeId = entity.getTypeId();
        if (typeId != null) {
            stmt.bindString(13, typeId);
        }
 
        String assetBrand = entity.getAssetBrand();
        if (assetBrand != null) {
            stmt.bindString(14, assetBrand);
        }
 
        String assetModel = entity.getAssetModel();
        if (assetModel != null) {
            stmt.bindString(15, assetModel);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OffLineAssetsBean readEntity(Cursor cursor, int offset) {
        OffLineAssetsBean entity = new OffLineAssetsBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // uid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // rfidId
            cursor.getInt(offset + 2), // assetState
            cursor.getInt(offset + 3), // permissionState
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // assetUser
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // belongDept
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // lastApproveUser
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // endTime
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // id
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // outBillId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // assetId
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // assetName
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // typeId
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // assetBrand
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14) // assetModel
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OffLineAssetsBean entity, int offset) {
        entity.setUid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRfidId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAssetState(cursor.getInt(offset + 2));
        entity.setPermissionState(cursor.getInt(offset + 3));
        entity.setAssetUser(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBelongDept(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLastApproveUser(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setEndTime(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setId(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setOutBillId(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setAssetId(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setAssetName(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTypeId(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setAssetBrand(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setAssetModel(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OffLineAssetsBean entity, long rowId) {
        entity.setUid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OffLineAssetsBean entity) {
        if(entity != null) {
            return entity.getUid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OffLineAssetsBean entity) {
        return entity.getUid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
